import React, { Component } from 'react';
import Scroll from '../common/scroll/Scroll';
import Lazyload, { forceCheck } from 'react-lazyload';
import axios from 'axios';
import URL from '../api/apiManger';


class OnShow extends Component {
  state = { 
    refreshScroll:false
   }
    getmovielist(){
    axios.get('v2/movie/in_theaters?apikey=0df993c66c0c636e29ecbb5344252a4a&start=0&count=10').then((res) =>{
      console.log(res)
    }).catch((err) =>{
      console.log(err)
    })
   }
   componentDidMount() {
    this.getmovielist()
   }
   
  render() { 
    const { refreshScroll } = this.state
      return (  
        <div className="onshow">
          <Scroll refresh={refreshScroll}>
          <div className="movielist">
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          <div>正在上映66</div>
          <div>正在上映</div>
          <div>正在上映88</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映889</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上映11</div>
          <div>正在上映</div>
          <div>正在55上映</div>
          <div>正在上5映</div>
          <div>正在上映</div>
          <div>正在上映22</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映</div>
          <div>正在上映</div>
          <div>正在5上映45</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在2上映33</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正2在上映</div>
          <div>正在上85映</div>
          <div>正在上映</div>
          <div>正在8上映</div>
          <div>正在上映</div>
          <div>正在5上映44</div>
          <div>正在上映</div>
          <div>正在上映</div>
          <div>正在上2映</div>
          <div>正在上映</div>
          <div>正在上映55</div>
          </div>
          </Scroll>
         
        </div>
      );
  }
}

export default OnShow;